llvm_major_version:
  - 15
 # error: 'shared_mutex' is unavailable: introduced in macOS 10.12
 MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
   - "12.5"                # [osx and x86_64]
 MACOSX_SDK_VERSION:        # [osx and x86_64]
   - "12.5"                # [osx and x86_64] 

version: "0.2.5"
enzyme_version: "0.0.150"